name: Node.js CI

on:
  # 워크플로 실행 시킬 이벤트 명시
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    # Ubuntu 최신 버전에서 실행
    runs-on: ubuntu-latest

    strategy:
      # 여러 Node.js 버전에서 테스트
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
      # 소스 코드 체크아웃
      - uses: actions/checkout@v4
      
      # Node.js 버전 설정
      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      # 간단한 출력 테스트
      - name: Print greeting
        run: echo "Hello!"
